#!/usr/bin/env bash
# Test plinth distribution installation via ghcup.
#
# Uses the experimental ghcup from ../ghcup-hs/ and the metadata
# generated by plinth-build.sh to install the plinth bindist into
# an isolated local environment.
#
# Usage:
#   ./plinth-ghcup-test.sh             # build ghcup, install & verify
#   GHCUP_BIN=/path/to/ghcup ./plinth-ghcup-test.sh  # use existing ghcup binary
#   SKIP_CLEANUP=1 ./plinth-ghcup-test.sh             # keep test environment
#   TUI=1 ./plinth-ghcup-test.sh                      # open ghcup tui after tests
#
set -euo pipefail

BASE="$PWD"

UNAME_S=$(uname -s)
case "$UNAME_S" in
    MINGW*|MSYS*) EXE_EXT=".exe" ;;
    *)            EXE_EXT="" ;;
esac

####################################################################
# configuration

: ${SKIP_CLEANUP:=0}
: ${TUI:=0}

# GHC used to build the experimental ghcup (not the plinth GHC)
: ${BUILD_GHC:=$(command -v ghc-9.6.7 2>/dev/null || command -v ghc 2>/dev/null || true)}
: ${CABAL:=$(command -v cabal 2>/dev/null || true)}

####################################################################
# locate the build artifacts from plinth-build.sh

BOOT_GHC="$BASE/_build/stage1/bin/ghc${EXE_EXT}"
if [ ! -x "$BOOT_GHC" ]; then
    echo "error: boot GHC not found at $BOOT_GHC"
    echo "       please run plinth-build.sh first"
    exit 1
fi

VERSION=$("$BOOT_GHC" --numeric-version)
TARGET_PLATFORM=$("$BOOT_GHC" --print-target-platform)
BINDIST_NAME="ghc-$VERSION-$TARGET_PLATFORM"

METADATA_FILE="$BASE/_build/bindist/$BINDIST_NAME-ghcup-metadata.yaml"
BINDIST_TARBALL="$BASE/_build/bindist/$BINDIST_NAME.tar.xz"

if [ ! -f "$METADATA_FILE" ]; then
    echo "error: ghcup metadata not found at $METADATA_FILE"
    echo "       please run plinth-build.sh first (metadata generation was added)"
    exit 1
fi
if [ ! -f "$BINDIST_TARBALL" ]; then
    echo "error: bindist tarball not found at $BINDIST_TARBALL"
    exit 1
fi

echo "test artifacts:"
echo "  version:  $VERSION"
echo "  platform: $TARGET_PLATFORM"
echo "  metadata: $METADATA_FILE"
echo "  tarball:  $BINDIST_TARBALL"

####################################################################
# build or locate the experimental ghcup

if [ -n "${GHCUP_BIN:-}" ] && [ -x "$GHCUP_BIN" ]; then
    echo "using provided ghcup: $GHCUP_BIN"
else
    echo "building experimental ghcup from ../ghcup-hs/..."

    if [ -z "$BUILD_GHC" ] || [ ! -x "$BUILD_GHC" ]; then
        echo "error: need a GHC to build ghcup (set BUILD_GHC)"
        exit 1
    fi
    if [ -z "$CABAL" ] || [ ! -x "$CABAL" ]; then
        echo "error: cabal not found (set CABAL)"
        exit 1
    fi

    GHCUP_BUILDDIR="$BASE/_build/ghcup-build"

    (
        cd "$BASE/../ghcup-hs"
        "$CABAL" build \
            -w "$BUILD_GHC" \
            --builddir="$GHCUP_BUILDDIR" \
            exe:ghcup
    )

    GHCUP_BIN=$(
        cd "$BASE/../ghcup-hs"
        "$CABAL" list-bin \
            -w "$BUILD_GHC" \
            --builddir="$GHCUP_BUILDDIR" \
            exe:ghcup
    )

    if [ ! -x "$GHCUP_BIN" ]; then
        echo "error: failed to build ghcup"
        exit 1
    fi
    echo "built ghcup: $GHCUP_BIN"
fi

####################################################################
# set up isolated test environment
#
# GHCUP_INSTALL_BASE_PREFIX controls where ghcup creates its
# .ghcup directory. By pointing it at a temporary directory we
# avoid touching any system-wide Haskell tooling.

TEST_DIR=$(mktemp -d "${TMPDIR:-/tmp}/plinth-ghcup-test.XXXXXX")

cleanup() {
    if [ "$SKIP_CLEANUP" -eq 1 ]; then
        echo "SKIP_CLEANUP=1: test environment preserved at $TEST_DIR"
    else
        echo "cleaning up test environment..."
        rm -rf "$TEST_DIR"
    fi
}
trap cleanup EXIT

export GHCUP_INSTALL_BASE_PREFIX="$TEST_DIR"
# Prevent ghcup from using any existing user configuration
export XDG_CONFIG_HOME="$TEST_DIR/config"
mkdir -p "$XDG_CONFIG_HOME"

echo ""
echo "=== isolated test environment ==="
echo "  GHCUP_INSTALL_BASE_PREFIX=$TEST_DIR"
echo "  ghcup dir: $TEST_DIR/.ghcup"
echo ""

####################################################################
# install plinth via ghcup using the generated metadata

echo "=== installing plinth $VERSION via ghcup ==="
"$GHCUP_BIN" --url-source "file://$METADATA_FILE" \
    install plinth "$VERSION"

echo ""
echo "=== verifying installation ==="

GHCUP_BIN_DIR="$TEST_DIR/.ghcup/bin"
INSTALL_DIR="$TEST_DIR/.ghcup/plinth/$VERSION"

# ghcup creates versioned symlinks in its bin dir (e.g. uplc-ghc-9.6.1501.20260305)
# and the actual binaries live under .ghcup/plinth/<version>/bin/
ALL_OK=1

# check that the install directory exists
if [ -d "$INSTALL_DIR" ]; then
    echo "  OK: install dir $INSTALL_DIR"
else
    echo "  MISSING: install dir $INSTALL_DIR"
    ALL_OK=0
fi

# check that the expected versioned symlinks were created in ghcup's bin dir
EXPECTED_BINS="uplc-ghc uplc-hsc2hs uplc-haddock uplc-hpc uplc-ghc-pkg uplc-hp2ps"
for bin in $EXPECTED_BINS; do
    VERSIONED="$bin-$VERSION"
    if [ -e "$GHCUP_BIN_DIR/$VERSIONED" ] || [ -L "$GHCUP_BIN_DIR/$VERSIONED" ]; then
        echo "  OK: $VERSIONED"
    else
        echo "  MISSING: $VERSIONED"
        ALL_OK=0
    fi
done

# verify versioned uplc-ghc runs
echo ""
UPLC_GHC="$GHCUP_BIN_DIR/uplc-ghc-${VERSION}${EXE_EXT}"
if [ -x "$UPLC_GHC" ] || [ -L "$UPLC_GHC" ]; then
    INSTALLED_VERSION=$("$UPLC_GHC" --numeric-version 2>&1 || true)
    if [ "$INSTALLED_VERSION" = "$VERSION" ]; then
        echo "  OK: uplc-ghc-$VERSION --numeric-version = $INSTALLED_VERSION"
    else
        echo "  FAIL: uplc-ghc-$VERSION --numeric-version returned '$INSTALLED_VERSION', expected '$VERSION'"
        ALL_OK=0
    fi
else
    echo "  FAIL: uplc-ghc-$VERSION is not executable at $UPLC_GHC"
    ALL_OK=0
fi

####################################################################
# set plinth as default and verify unversioned symlinks

echo ""
echo "=== setting plinth $VERSION as default ==="
"$GHCUP_BIN" --url-source "file://$METADATA_FILE" \
    set plinth "$VERSION"

echo ""
echo "=== verifying unversioned symlinks ==="
for bin in $EXPECTED_BINS; do
    if [ -e "$GHCUP_BIN_DIR/$bin" ] || [ -L "$GHCUP_BIN_DIR/$bin" ]; then
        echo "  OK: $bin"
    else
        echo "  MISSING: $bin"
        ALL_OK=0
    fi
done

# verify unversioned uplc-ghc runs
echo ""
UPLC_GHC_DEFAULT="$GHCUP_BIN_DIR/uplc-ghc${EXE_EXT}"
if [ -x "$UPLC_GHC_DEFAULT" ] || [ -L "$UPLC_GHC_DEFAULT" ]; then
    INSTALLED_VERSION=$("$UPLC_GHC_DEFAULT" --numeric-version 2>&1 || true)
    if [ "$INSTALLED_VERSION" = "$VERSION" ]; then
        echo "  OK: uplc-ghc --numeric-version = $INSTALLED_VERSION"
    else
        echo "  FAIL: uplc-ghc --numeric-version returned '$INSTALLED_VERSION', expected '$VERSION'"
        ALL_OK=0
    fi
else
    echo "  FAIL: uplc-ghc is not executable at $UPLC_GHC_DEFAULT"
    ALL_OK=0
fi

echo ""
if [ "$ALL_OK" -eq 1 ]; then
    echo "=== ALL TESTS PASSED ==="
else
    echo "=== SOME TESTS FAILED ==="
    echo "  inspect: $TEST_DIR/.ghcup/"
    SKIP_CLEANUP=1  # preserve for debugging
    exit 1
fi

####################################################################
# optional: drop into ghcup tui

if [ "$TUI" -eq 1 ]; then
    echo ""
    echo "=== launching ghcup tui ==="
    echo "  (isolated environment at $TEST_DIR/.ghcup)"
    "$GHCUP_BIN" --url-source "file://$METADATA_FILE" tui || true
fi
